import {
  MailOutline,
  SettingOutline,
  AppstoreOutline,
  DashboardOutline,
  HomeOutline,
  ApartmentOutline,
  LoadingOutline,
  BugOutline,
  ReloadOutline,
  DeploymentUnitOutline,
  SendOutline,
  WalletOutline,
  CopyOutline,
  TwitterOutline,
  GlobalOutline,
} from "@ant-design/icons-angular/icons";

export const ICONS_AUTO = [
  MailOutline,
  SettingOutline,
  AppstoreOutline,
  DashboardOutline,
  HomeOutline,
  ApartmentOutline,
  LoadingOutline,
  BugOutline,
  ReloadOutline,
  DeploymentUnitOutline,
  SendOutline,
  WalletOutline,
  CopyOutline,
  TwitterOutline,
  GlobalOutline,
];
